import { EntitySchema } from 'typeorm';

export const AuditEvent = new EntitySchema({
  name: 'AuditEvent',
  tableName: 'audit_events',
  columns: {
    id: { type: 'uuid', primary: true, generated: 'uuid' },
    event_id: { type: 'text' },
    timestamp: { type: 'timestamptz' },
    category: { type: 'text' },
    action: { type: 'text' },
    severity: { type: 'text' },
    description: { type: 'text', nullable: true },
    user_id: { type: 'uuid', nullable: true },
    session_id: { type: 'text', nullable: true },
    ip_address: { type: 'text', nullable: true },
    user_agent: { type: 'text', nullable: true },
    actor_type: { type: 'text', nullable: true },
    resource_type: { type: 'text', nullable: true },
    resource_id: { type: 'text', nullable: true },
    resource_name: { type: 'text', nullable: true },
    endpoint: { type: 'text', nullable: true },
    http_method: { type: 'text', nullable: true },
    status_code: { type: 'int', nullable: true },
    response_time: { type: 'int', nullable: true },
    request_size: { type: 'int', nullable: true },
    response_size: { type: 'int', nullable: true },
    success: { type: 'boolean', default: true },
    error_code: { type: 'text', nullable: true },
    error_message: { type: 'text', nullable: true },
    risk_score: { type: 'int', default: 0 },
    is_suspicious: { type: 'boolean', default: false },
    security_flags: { type: 'jsonb', nullable: true },
    geolocation: { type: 'jsonb', nullable: true },
    business_data: { type: 'jsonb', nullable: true },
    sensitive_data: { type: 'jsonb', nullable: true },
    server_name: { type: 'text', nullable: true },
    environment: { type: 'text', nullable: true },
    created_at: { type: 'timestamptz', createDate: true },
  },
  indices: [
    { columns: ['event_id'], unique: true },
    { columns: ['timestamp'] },
  ],
});
