name: Build iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get
        working-directory: mosombi_frontend

      - name: Build iOS
        run: flutter build ios --release --no-codesign
        working-directory: mosombi_frontend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: mosombi_frontend/build/ios/iphoneos/
